services:
  microsoft-rewards-script:
    build: .
    container_name: microsoft-rewards-script
    environment:
      NODE_ENV: production
      HEADLESS: true
      TZ: Europe/Berlin
    restart: unless-stopped
    volumes:
      ### Replace "/path/to/" with the actual path to where you want to save the files on your local machine.
      - ./config/accounts.json:/usr/src/microsoft-rewards-script/dist/accounts.json
      - ./config/config.json:/usr/src/microsoft-rewards-script/dist/config.json
      - ./sessions:/microsoft-rewards-script/dist/browser/config/sessions
      - /etc/localtime:/etc/localtime:ro